twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      # navigation:
      #   topic   : cmd_vel_tracker
      #   timeout : 0.5
      #   priority: 20
      tracking:
        topic   : cmd_vel_tracking
        timeout : 0.5
        priority: 50
      # joystick:
      # # for using joystick
      #   topic   : cmd_vel_joy
      #   timeout : 0.5
      #   priority: 100